#pragma config(StandardModel, "RVW CLAWBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

#define DEBUG

#include "../Enterprise.c"
#include "./Shimakaze.c"

replay_t replay;

void pre_auton() {}

task autonomous() {
    control_t state;

    initReplayData(&replay);

    loadReplayFromFile("replay", &replay);

    while(1) {
        replayToControl(&state, &replay);
        controlToMotors(state);

        sleep(deltaT);
    }
}

task usercontrol() {
    control_t state;

    initReplayData(&replay);

    while(1) {
        joystickToControl(&state);
        controlToMotors(state);
        controlToReplay(state, &replay);

        if(vexRT[Btn7L]) {
            break;
        }

        sleep(deltaT);
    }

    saveReplayToFile("replay", &replay);
}
