#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, in2,    autoSelector,   sensorPotentiometer)
#pragma config(Sensor, in3,    posSelector,    sensorPotentiometer)
#pragma config(Sensor, dgtl1,  catapultLim,    sensorTouch)
#pragma config(Sensor, dgtl2,  upperLim,       sensorTouch)
#pragma config(Sensor, I2C_1,  leftEnc,        sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  rightEnc,       sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           RBack,         tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           RFront,        tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port3,           rightLowerIntake, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightUpperIntake, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           hangMotor,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           leftUpperIntake, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           leftLowerIntake, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           LFront,        tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port10,          LBack,         tmotorVex393HighSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

#include "./Enterprise.c"
#include "./Akagi.c"
/* Competition control stub. */

void loadAutonomous(replayData* replay) {
	int pos = sensorValue[autoSelector];

	if(pos < 727) {		// Illuminati Skills
		writeDebugStreamLine("Loading: ilmskills");
		loadReplayFromFile("ilmskills", replay);
	} else if(pos < 1920) {	// Illuminati routine
		writeDebugStreamLine("Loading: ilmroutine");
		loadReplayFromFile("ilmroutine", replay);
	} else if(pos < 2678) {	// Off
		return;
	} else if(pos < 3200) {	// A1
		writeDebugStreamLine("Loading: slot1");
		loadReplayFromFile("slot1", replay);
	} else if(pos < 3768) { // A2
		writeDebugStreamLine("Loading: slot2");
		loadReplayFromFile("slot2", replay);
	} else if(pos > 4080) {	// A3
		writeDebugStreamLine("Loading: slot3");
		loadReplayFromFile("slot3", replay);
	}

	clearLCDLine(0);
	displayLCDCenteredString(0, "Load done.");
	writeDebugStreamLine("Loading done.");
}

void pre_auton()
{
	loadReplayFromFile(compFilename, &replay);
}

task autonomous() {
    clearReplay();
    loadAutonomous(&replay);

	initState();
	while(replay.streamIndex < replay.streamSize) {
		replayToControlState();
		controlLoopIteration();
		sleep((int)deltaT);
	}

	stopAllMotors();
}

task usercontrol()
{
	resetState();

	while (true)
	{
		controllerToControlState();
		controlLoopIteration();
		sleep((int)deltaT);
	}
}
