#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, in2,    autoSelector,   sensorPotentiometer)
#pragma config(Sensor, in3,    posSelector,    sensorPotentiometer)
#pragma config(Sensor, dgtl1,  catapultLim,    sensorTouch)
#pragma config(Sensor, dgtl2,  upperLim,       sensorTouch)
#pragma config(Sensor, I2C_1,  leftEnc,        sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  rightEnc,       sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           RBack,         tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           RFront,        tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port3,           rightLowerIntake, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightUpperIntake, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           hangMotor,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           leftUpperIntake, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           leftLowerIntake, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           LFront,        tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port10,          LBack,         tmotorVex393HighSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

#include "../Enterprise.c"
#include "./Akagi.c"
/* Competition control stub. */

bool enableLCD = true;

control_t state;
replay_t replay;

int currentTime = 0;
int replayTime = 0;

task lcdUpdate() {
    while(true) {
        clearLCDLine(1);

        if(currentTime > 0) {
            int sec = currentTime / 1000;
            int ms = currentTime % 1000;

            displayLCDString(1, 0, "Time: "); // length 5 (next char at 6)

            /* Displays: ss.mmm (ss = seconds, mmm = milliseconds) */
            displayLCDNumber(1, 6, sec, 2);
            displayLCDChar(1, 8, '.');
            displayLCDNumber(1, 9, sec, -3);
        }

        if(replayTime > 0) {
            int sec = replayTime / 1000;
            int ms = replayTime % 1000;

            displayLCDString(1, 12, " / ");

            displayLCDNumber(1, 15, sec, 2);
            displayLCDChar(1, 17, '.');
            displayLCDNumber(1, 18, sec, -3);
        }

        sleep(deltaT);
    }
}

void pre_auton() {
    initReplayData(&replay);
    loadAutonomous(&replay);
	initState(&state);

    if(enableLCD) {
        startTask(lcdUpdate);
    }
}

task autonomous() {
    currentTime = 0;    // current elapsed milliseconds
    replayTime = getReplayTime(&replay);

	while(replay.streamIndex < replay.streamSize) {
		replayToControlState(&state, &replay);
		controlLoopIteration(&state);

        currentTime += (int)deltaT;

		sleep((int)deltaT);
	}

	stopAllMotorsCustom();
}

task usercontrol()
{
	resetState(&state);

    currentTime = 0;
    replayTime = 0;

	while (true)
	{
		controllerToControlState(&state);
		controlLoopIteration(&state);

        currentTime += (int)deltaT;

		sleep((int)deltaT);
	}
}
