#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, in2,    autoSelector,   sensorPotentiometer)
#pragma config(Sensor, in3,    posSelector,    sensorPotentiometer)
#pragma config(Sensor, dgtl1,  catapultLim,    sensorTouch)
#pragma config(Sensor, dgtl2,  upperLim,       sensorTouch)
#pragma config(Sensor, I2C_1,  leftEnc,        sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  rightEnc,       sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           RBack,         tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           RFront,        tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port3,           rightLowerIntake, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightUpperIntake, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           hangMotor,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           leftUpperIntake, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           leftLowerIntake, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           LFront,        tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port10,          LBack,         tmotorVex393HighSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

#define DEBUG

#include "../Enterprise.c"
#include "./RedCastle.c"
/* Recorder control stub. */

void loadAutonomous(replayData* replay) {
	int pos = sensorValue[autoSelector];

	if(pos < 727) {		// Illuminati Skills
		writeDebugStreamLine("Loading: ilmskills");
		loadReplayFromFile("ilmskills", replay);
	} else if(pos < 1920) {	// Illuminati routine
		writeDebugStreamLine("Loading: ilmroutine");
		loadReplayFromFile("ilmroutine", replay);
	} else if(pos < 2678) {	// Off
		return;
	} else if(pos < 3200) {	// A1
		writeDebugStreamLine("Loading: slot1");
		loadReplayFromFile("slot1", replay);
	} else if(pos < 3768) { // A2
		writeDebugStreamLine("Loading: slot2");
		loadReplayFromFile("slot2", replay);
	} else if(pos > 4080) {	// A3
		writeDebugStreamLine("Loading: slot3");
		loadReplayFromFile("slot3", replay);
	}

	clearLCDLine(0);
	displayLCDCenteredString(0, "Load done.");
	writeDebugStreamLine("Loading done.");
}

void saveAutonomous(replayData* replay) {
	int pos = sensorValue[autoSelector];

	if(pos < 727) {		// Illuminati Skills
		writeDebugStreamLine("Saving: ilmskills");
		saveReplayToFile("ilmskills", replay);
	} else if(pos < 1920) {	// Illuminati routine
		writeDebugStreamLine("Saving: ilmroutine");
		saveReplayToFile("ilmroutine", replay);
	} else if(pos < 2678) {	// Off
		return;
	} else if(pos < 3200) {	// A1
		writeDebugStreamLine("Saving: slot1");
		saveReplayToFile("slot1", replay);
	} else if(pos < 3768) { // A2
		writeDebugStreamLine("Saving: slot2");
		saveReplayToFile("slot2", replay);
	} else if(pos > 4080) {	// A3
		writeDebugStreamLine("Saving: slot3");
		saveReplayToFile("slot3", replay);
	}

	clearLCDLine(0);
	displayLCDCenteredString(0, "Save done.");
	writeDebugStreamLine("Saving done.");
}

void pre_auton() {
}

task autonomous() {
	clearReplay();

	loadAutonomous(&replay);

	replay.streamIndex = 0;
	initState();

	while(replay.streamIndex < replay.streamSize) {
		replayToControlState();
		controlLoopIteration();
		sleep((int)deltaT);
	}

	stopAllMotorsCustom();
}

unsigned int currentTime = 0;

/* Max recording time in milliseconds.
 *
 *  For a regular match autonomous recording, this should be 15000 milliseconds (= 15 seconds).
 *  For an Auto Skills recording, this should be 60000 milliseconds (= 60 seconds = 1 minute).
 */
unsigned int timelimit = 61000;

task usercontrol()
{
	initState();
	clearReplay();

	clearLCDLine(0);
	clearLCDLine(1);
	displayLCDCenteredString(0, "Ready to record.");
	displayLCDCenteredString(1, "Do stuff.");

	while (true)
	{
		if(abs(vexRT[Ch2]) > deadband || abs(vexRT[Ch1]) > deadband) {
			break;
		}

		if(vexRT[Btn6D] || vexRT[Btn6U] || vexRT[Btn7U] ||
		   vexRT[Btn5U] || vexRT[Btn5D] || vexRT[Btn8U] || vexRT[Btn8D])
		{
			break;
		}

		sleep(5);
	}

	clearLCDLine(0);
	clearLCDLine(1);
	displayLCDCenteredString(0, "Recording...");

	while (true)
	{
		controllerToControlState();
		controlLoopIteration();

		if(timelimit > 0) {
			controlStateToReplay();
		}

		currentTime += (int)deltaT;

		if(vexRT[Btn7L]) {
			break;
		}

		if((currentTime > timelimit) && (timelimit > 0)) {
			break;
		}

		sleep((int)deltaT);
	}

	replay.streamSize = replay.streamIndex+1;

	stopAllMotorsCustom();

	bool doSave = false;
	while(true) {
		displayLCDCenteredString(0, "Save replay?");
		if(!doSave) {
			displayLCDCenteredString(1, "[No] Yes ");
		} else {
			displayLCDCenteredString(1, " No [Yes]");
		}

		if(nLCDButtons & 0x01) {
			doSave = false;
		} else if(nLCDButtons & 0x02) {
			break;
		} else if(nLCDButtons & 0x04) {
			doSave = true;
		}
	}

	if(doSave) {
		saveAutonomous(&replay);
	}

    RCFS_ReadVTOC();
}
