#pragma config(Sensor, in1,    pot,            sensorPotentiometer)
#pragma config(Sensor, dgtl1,  ,               sensorQuadEncoder)
#pragma config(Motor,  port1,           rightDrivea,   tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           rightDriveb,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           clawR,         tmotorVex393_MC29, PIDControl, encoderPort, dgtl1)
#pragma config(Motor,  port4,           ArmRb,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           ArmRt,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           ArmLt,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           ArmLa,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           clawL,         tmotorVex393_MC29, PIDControl, encoderPort, dgtl1)
#pragma config(Motor,  port9,           leftDrivea,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          leftDriveb,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

#include "../Enterprise.c"
#include "./Warspite.c"

void pre_auton() {
}

task autonomous() {
    control_t state;
    replay_t replay;

	initReplayData(&replay);
    initState(&replay);
	loadAutonomous(&replay);

	while(replay.streamIndex < replay.streamSize) {
		replayToControlState(&replay);
		controlLoopIteration(&state);
		sleep((int)deltaT);
	}

	stopAllMotorsCustom();
}

unsigned int currentTime = 0;

/* Max recording time in milliseconds.
 *
 *  For a regular match autonomous recording, this should be 15000 milliseconds (= 15 seconds).
 *  For an Auto Skills recording, this should be 60000 milliseconds (= 60 seconds = 1 minute).
 */
unsigned int timelimit = 61000;

task usercontrol()
{
    control_t state;
    replay_t replay;

	initState(&state);

	clearLCDLine(0);
	clearLCDLine(1);
	displayLCDCenteredString(0, "Ready to record.");
	displayLCDCenteredString(1, "Do stuff.");

	while (true)
	{
        joystickToControl(&state);
		if( abs(state.left) > deadband || abs(state.right) > deadband
            || state.armUp || state.armDown || state.clawOpen || state.clawClose
        ) {
            break;
        }

		sleep(5);
	}

	clearLCDLine(0);
	clearLCDLine(1);
	displayLCDCenteredString(0, "Recording...");

    resetState(&state);

	while (true)
	{
		joystickToControl(&state);
		controlLoopIteration(&state);

		if(timelimit > 0) {
			controlStateToReplay(&state, &replay);
		}

		currentTime += (int)deltaT;

		if((currentTime > timelimit) && (timelimit > 0)) {
			break;
		}

		sleep((int)deltaT);
	}

	replay.streamSize = replay.streamIndex+1;

	stopAllMotorsCustom();

	bool doSave = false;
	while(true) {
		displayLCDCenteredString(0, "Save replay?");
		if(!doSave) {
			displayLCDCenteredString(1, "[No] Yes ");
		} else {
			displayLCDCenteredString(1, " No [Yes]");
		}

		if(nLCDButtons & 0x01) {
			doSave = false;
		} else if(nLCDButtons & 0x02) {
			break;
		} else if(nLCDButtons & 0x04) {
			doSave = true;
		}
	}

	if(doSave) {
		saveReplayToFile("replay", &replay);
	}

    RCFS_ReadVTOC();
}
